name: "Release"

permissions:
  id-token: write
  issues: write
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
jobs:
  release_semver:
    uses: ./.github/workflows/release_semver.yml
